### ISSUE TITLE
[FR] Run all

### ISSUE THREAD

**Issue by gustaphe** [compleathorseplayer/Neptune.jl#19]
(If this feature exists, it needs to be documented) (if this feature exists and is documented, I need to get my eyes checked)

Button or button combination to run all cells. Especially useful for markdown-heavy notebooks with hidden source, where the alternative is to unhide the source for every cell in order, run them and then hide the source again, on every fresh open.

**Comment by lnacquaroli** [comment]
Something like this, `Neptune.run(run_notebook_on_load=true)`? (see [here](https://discourse.julialang.org/t/announcing-neptune-jl-now-updated-to-multi-line-cells/54088/70))

Not sure if it's documented but can be included.

**Comment by gustaphe** [comment]
That works, yes.
