### ISSUE TITLE
license

### ISSUE THREAD

**Issue by fonsp** [compleathorseplayer/Neptune.jl#7]
You can't change the original license (and claim copyright), you need to include a _copy_ of the original, together with your new license. state clearly that this is a fork of Pluto.

https://github.com/fonsp/Pluto.jl/blob/af0c0a6ef3b6a453f8df96906999471eb04018ed/LICENSE#L12-L13

**Comment by Sov-trotter** [comment]
Oh my bad. Thanks alot for pointing this out! :)

**Comment by Sov-trotter** [comment]
Hey @fonsp can you check if this is correct?
